# Generated by Django 5.0.7 on 2024-08-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
