# Generated by Django 5.0.7 on 2024-08-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_replied',
            field=models.BooleanField(default=False),
        ),
    ]
