# Generated by Django 5.0.7 on 2024-08-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_contactus_is_replied'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
