# Generated by Django 5.0.7 on 2024-07-24 05:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ProductAttributeValue',
                'verbose_name_plural': 'ProductAttributeValues',
            },
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='value',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.productattribute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_value',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.productattributevalue'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
    ]
