# Generated by Django 5.0.7 on 2024-07-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('value', 'product')},
        ),
    ]
