# Generated by Django 5.0.7 on 2024-07-31 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_sub_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category', 'sub_category')},
        ),
    ]
