# Generated by Django 5.0.7 on 2024-07-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
    ]
