# Generated by Django 5.0.7 on 2024-08-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productimage_created_at_productimage_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='product.productattribute'),
        ),
    ]
