# Generated by Django 5.0.7 on 2024-08-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productattributevalue_product_attribute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
