# Generated by Django 5.0.7 on 2024-08-01 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together=set(),
        ),
    ]
