# Generated by Django 5.0.7 on 2024-08-02 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productattributevalue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='product.productattribute'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='productattributevalue',
            unique_together={('value', 'product')},
        ),
    ]
