# Generated by Django 5.0.7 on 2024-08-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_order_order_id_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_cash_on_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.IntegerField(choices=[(1, 'Standard Shipping'), (2, 'Express Shipping'), (3, 'Overnight Shipping'), (4, 'Pickup')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING'), (4, 'REFUNDED'), (5, 'DISPUTED'), (6, 'CASH_ON_DELIVERY')], default=3),
        ),
    ]
