# Generated by Django 5.0.7 on 2024-08-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productincart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productincart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ProductInCart',
        ),
        migrations.DeleteModel(
            name='ProductInOrder',
        ),
    ]
