# Generated by Django 5.0.7 on 2024-08-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_review_title_alter_review_email_alter_review_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
