# Generated by Django 5.0.7 on 2024-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_remove_review_email_remove_review_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_features',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
