# Generated by Django 5.0.7 on 2024-09-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productimage_is_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_features',
        ),
        migrations.AddField(
            model_name='product',
            name='is_features',
            field=models.BooleanField(default=False),
        ),
    ]
