# Generated by Django 5.0.7 on 2024-08-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('users', '0006_address_is_primary_alter_address_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_address', to='users.address'),
            preserve_default=False,
        ),
    ]
