# Generated by Django 5.0.7 on 2024-09-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
