# Generated by Django 5.0.7 on 2024-10-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_estimated_delivery_date_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_cash_on_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Online'), (2, 'Cash on Delivery')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING'), (4, 'REFUNDED'), (5, 'DISPUTED')], default=3),
        ),
    ]
