# Generated by Django 5.0.7 on 2024-10-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_is_cash_on_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Paypal'), (2, 'Cash on Delivery')], default=1),
        ),
    ]
