# Generated by Django 5.0.7 on 2024-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Unique coupon code', max_length=150, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed discount amount', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount', max_digits=5)),
                ('start_date', models.DateField(help_text='Start date of the coupon validity')),
                ('end_date', models.DateField(help_text='End date of the coupon validity')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is active or not')),
                ('is_delete', models.BooleanField(default=False, help_text='Whether the coupon is delete or not')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
