# Generated by Django 5.0.7 on 2024-09-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_coupon_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_delete',
            field=models.BooleanField(default=False, help_text='Whether the coupon is deleted or not'),
        ),
    ]
