# Generated by Django 5.0.7 on 2024-07-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_numer',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
