# Generated by Django 5.0.7 on 2024-07-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone_numer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
